### ISSUE TITLE
QA 3: Issue with the Dashboard

### ISSUE THREAD

**Issue by Cassandra-Mae-Patel** [Khasaleh/family_app#26]
Steps to reproduce:

1. logged in to the account (username/password)

actual result: No matter what the user name we use, the dashboard only shows. "Hello, Khaled!"

expected results: Should display the "username" instead of "Khaled"

picture to support the above mentioned issue:
![image](https://user-images.githubusercontent.com/77755295/139497683-3b14afa5-c131-4846-af09-d03887d58726.png)

**Comment by Khasaleh** [comment]
fixed
