### ISSUE TITLE
QA 5: Issue with the chat option

### ISSUE THREAD

**Issue by Cassandra-Mae-Patel** [Khasaleh/family_app#28]
Steps to reproduce:

1. logged in to the account (username/password)
2. Click on Chat option in the navigation tab

actual result: Chat tab looks same as the Gallery tab. (Chat tab only has fields to look at images and date uploaded.)
expected results: There should be area for the users to chat in with the timestamp.

picture to support the above mentioned issue:
![image](https://user-images.githubusercontent.com/77755295/139499535-37df901a-cff9-40f5-a9dc-a54ddebe30c8.png)

**Comment by Khasaleh** [comment]
fixed
