### ISSUE TITLE
QA 6 :Issue with date of birth validation.

### ISSUE THREAD

**Issue by ksnigs** [Khasaleh/family_app#29]
**Steps to reproduce:**

1.sign up in to the account
2. navigate to page  < http://qa.fazeal.com/signup>
3. Dob is not taking properly

**actual results:** 

user is able to add the date in weird format as specified in the image

**expected results**: 
the date of birth format should be 
DD/MM/YYYY

the DOB shouldn't be current or in the future. minimum age to sign up should be 5 years old.

![image](https://user-images.githubusercontent.com/89712609/139505904-5d47cbd3-f044-4833-9ed0-b64870836c7e.png)

**Comment by ksnigs** [comment]
Steps to reproduce:
1.sign up in to the account 
2.navigat to page < mention the page >
3, Dob is not taking properly
actual results: It need to be implemented either the person should the dob from the calendar itself.

expected results: By typing it is taking so numbers

**Comment by Khasaleh** [comment]
please retest

**Comment by Khasaleh** [comment]
fixed
