### ISSUE TITLE
QA 7 : Issue with email validation at signup form

### ISSUE THREAD

**Issue by ksnigs** [Khasaleh/family_app#30]
**Steps to reproduce:**

1. go to  http://qa.fazeal.com/signup
2. fill all the fields with accurate information.
3. put in the email field ( user@user ) without ( .com )

actual result: without typing .com also it is getting signedup. it is accepting with uncomplete email information.

**expected results:** 
error showing on top of the email input box indicating it is not expected email format.

**The email should be in a format which is existed like .com web address need to included.**

![image](https://user-images.githubusercontent.com/89712609/139506470-f5163c0e-6875-4652-95f3-ac0591325ae3.png)

**Comment by Khasaleh** [comment]
please try on email rest functionality @ksnigs

**Comment by Khasaleh** [comment]
work in progress ... now we are working on the templates.

**Comment by Khasaleh** [comment]
fixed
