### ISSUE TITLE
QA 8: No email sent upon SignUp

### ISSUE THREAD

**Issue by Cassandra-Mae-Patel** [Khasaleh/family_app#31]
Steps to reproduce:
- Go to webpage of Fazeal (http://qa.fazeal.com/login)
- Click on Sign Up
- Fill in the accurate details.
- Click on Sign Up

actual result: No email received from the web app Fazeal though got the message of successful sign up.
expected results: An email must be sent to the user's email address.

picture to support the above mentioned issue:
-NA-

**Comment by Khasaleh** [comment]
Still work in progress, but email password reset get sent

**Comment by Khasaleh** [comment]
fixed
