### ISSUE TITLE
QA 9: Issue with the uploaded image in the Gallery

### ISSUE THREAD

**Issue by Cassandra-Mae-Patel** [Khasaleh/family_app#32]
Steps to reproduce:

- logged in to the account (username/password)
- Click on the upload option from the navigation panel
- Select the file to be uploaded
- Click on the upload button.
- Click on the Gallery option from the navigation panel

actual result: Shows the checkbox and the Date Uploaded for the image but, no image is found in the Gallery
expected results: There should be an entry for image under the `Image` column in the Gallery.

picture to support the above mentioned issue:
![image](https://user-images.githubusercontent.com/77755295/140231862-dd33a654-e7c7-4f20-b2a7-77b48711d05e.png)

**Comment by Khasaleh** [comment]
fixed
