### ISSUE TITLE
QA 10: Issue with visibility of password (Suggestion)

### ISSUE THREAD

**Issue by Cassandra-Mae-Patel** [Khasaleh/family_app#33]
Steps to reproduce:
- Go to the webpage link: http://qa.fazeal.com/login

actual result: Field for password doesn't have the option of hide/unhide password.
expected results: There should be an option for hide/unhide password for the ease of user - to type in the password.

picture to support the above mentioned issue:
![image](https://user-images.githubusercontent.com/77755295/140589265-5c76b038-4f47-4eeb-a287-bcc957f89b97.png)

**Comment by Khasaleh** [comment]
@Cassandra-Mae-Patel  please retest

**Comment by Khasaleh** [comment]
fixed
